apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dag-test-2023-07-12.20-42-43
  namespace: argo
spec:
  entrypoint: start
  templates:
    - name: start
      dag:
        tasks:
          - name: casbin
            template: casbin
            dependencies: []
          - name: lens
            template: lens
            dependencies: []
          - name: notifyer-deploy
            template: notifyer-deploy
            dependencies: []
          - name: kubewatch
            template: kubewatch
            dependencies: []
          - name: kubelink
            template: kubelink
            dependencies: []
          - name: app-sync-cronjob
            template: app-sync-cronjob
            dependencies: []
          - name: image-scanner
            template: image-scanner
            dependencies: []
          - name: orchestrator
            template: orchestrator
            dependencies: ['casbin', 'kubelink', 'kubewatch', 'lens', 'image-scanner']
          - name: dashboard
            template: dashboard
            dependencies: ['orchestrator']
    - name: casbin
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "17"
          - name: CD_PIPELINE_ID
            value: "46"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "90"
    - name: lens
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "12"
          - name: CD_PIPELINE_ID
            value: "21"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "86"
    - name: notifyer-deploy
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "16"
          - name: CD_PIPELINE_ID
            value: "41"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "92"
    - name: kubewatch
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "13"
          - name: CD_PIPELINE_ID
            value: "26"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "84"
    - name: kubelink
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "14"
          - name: CD_PIPELINE_ID
            value: "31"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "85"
    - name: app-sync-cronjob
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "18"
          - name: CD_PIPELINE_ID
            value: "51"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "91"
    - name: image-scanner
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "15"
          - name: CD_PIPELINE_ID
            value: "36"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "89"
    - name: orchestrator
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "8"
          - name: CD_PIPELINE_ID
            value: "8"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "87"
    - name: dashboard
      container:
        image: badal773/release:08
        env:
          - name: APPID
            value: "11"
          - name: CD_PIPELINE_ID
            value: "16"
          - name: ENVID
            value: "1"
          - name: CI_ARTIFACT_ID
            value: "103"
