name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read current version
        id: read_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Increment version
        id: increment_version
        run: echo "::set-output name=version::$(echo $(cat version.txt) | awk -F. '{printf "v%d.%d.%d", $1, $2, $3 + 1}')"

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.increment_version.outputs.version }}
          release_name: Release ${{ steps.increment_version.outputs.version }}
          body: |
            Add release notes here.

      - name: Update version.txt
        run: echo "${{ steps.increment_version.outputs.version }}" > version.txt
